// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlVo2ivkmTEgGos4jU9abtSGMBMdVqrzs',
    appId: '1:184250420702:web:e78c5140ac18ba2219614f',
    messagingSenderId: '184250420702',
    projectId: 'todo-app-e6942',
    authDomain: 'todo-app-e6942.firebaseapp.com',
    storageBucket: 'todo-app-e6942.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA00ZEM_3pVXaPdn0_k-QI9yBci7YY_Irw',
    appId: '1:184250420702:android:8f5ac414ffbaa72219614f',
    messagingSenderId: '184250420702',
    projectId: 'todo-app-e6942',
    storageBucket: 'todo-app-e6942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCcXgwydnuV2I-jHjYxTg8PwViqBD6Hg',
    appId: '1:184250420702:ios:efc3115a37df803819614f',
    messagingSenderId: '184250420702',
    projectId: 'todo-app-e6942',
    storageBucket: 'todo-app-e6942.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyCcXgwydnuV2I-jHjYxTg8PwViqBD6Hg',
    appId: '1:184250420702:ios:efc3115a37df803819614f',
    messagingSenderId: '184250420702',
    projectId: 'todo-app-e6942',
    storageBucket: 'todo-app-e6942.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlVo2ivkmTEgGos4jU9abtSGMBMdVqrzs',
    appId: '1:184250420702:web:b8bfe474b4f7822d19614f',
    messagingSenderId: '184250420702',
    projectId: 'todo-app-e6942',
    authDomain: 'todo-app-e6942.firebaseapp.com',
    storageBucket: 'todo-app-e6942.appspot.com',
  );
}
